name: main

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target: ["x86_64-unknown-linux-gnu"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      -
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true
      -
        name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      -
        name: Set tag name in environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      -
        name: Set lowercase repository in environment
        run: echo "REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      - 
        name: Debugging in prod
        run: ls -alh target/${{ matrix.target }}/release
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Create and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          no-cache: true
          context: .
          build-args: |
            TARGET_TRIPLE=${{ matrix.target }}
          tags: |
            ghcr.io/${{ env.REPOSITORY_LOWERCASE }}:latest
            ghcr.io/${{ env.REPOSITORY_LOWERCASE }}:${{ env.RELEASE_VERSION }}
